export const MAIN_LINKS_FRONTEND = {
    HOME: process.env.REACT_APP_LINK_MAIN_HOME,
    AUTH: process.env.REACT_APP_LINK_MAIN_AUTH,
    CHECKOUT: process.env.REACT_APP_LINK_MAIN_CHECKOUT,
    ACCOUNT_INFO: process.env.REACT_APP_LINK_MAIN_ACCOUNT_INFO,
}

export const ADMIN_LINKS_FRONTEND = {
    INDEX: process.env.REACT_APP_LINK_ADMIN_INDEX,
    USER: process.env.REACT_APP_LINK_ADMIN_USER,
    USERS: process.env.REACT_APP_LINK_ADMIN_USERS,
    CATEGORIES: process.env.REACT_APP_LINK_ADMIN_CATEGORIES,
    ADD_CATEGORY: process.env.REACT_APP_LINK_ADMIN_ADD_CATEGORY,
    ADD_PRODUCTS: process.env.REACT_APP_LINK_ADMIN_ADD_PRODUCTS,
}